// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxguchtwmrtrkruhxrqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4Z3VjaHR3bXJ0cmtydWh4cnFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzU5NDYsImV4cCI6MjA3MTcxMTk0Nn0.K2N1z_OUsFoji_h-5f9MqViYs9voGSqkfHyEt0n1rUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});